name: Sample Workflow

on: push

jobs:
  demo:
    name: test-job
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v5

    - name: Display the path
      shell: bash
      run: echo ${{ github.token }}
    
